//Motorcycle
export const SELECT_BRAND = 'SELECT_BRAND';
export const SELECT_BIKES = 'SELECT_BIKES';

//Form
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const START_CONFIRMATION = 'START_CONFIRMATION';
export const CANCEL_CONFIRMATION = 'CANCEL_CONFIRMATION';

export const RENT_START = 'RENT_START';
export const RENT_SUCCES = 'RENT_SUCCES';
export const RENT_FAIL = 'RENT_FAIL';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCES = 'FETCH_ORDERS_SUCCES';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const FETCH_USER_ORDERS_SUCCESS = 'FETCH_USER_ORDERS_SUCCESS';

export const DELETE_ITEM_START = 'DELETE_ITEM_START';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAIL = 'DELETE_ITEM_FAIL';

export const CLEAR_ORDERS_ARR = 'CLEAR_ORDERS_ARR';

export const GET_ORDERS_OF_THE_DAY = 'GET_ORDERS_OF_THE_DAY';

//Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL =  'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';